# Generated by Django 2.0.4 on 2018-05-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0005_remove_instruments_id_sale'),
        ('sales', '0004_auto_20180521_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='id_sale_Instrument',
            field=models.ManyToManyField(to='instruments.Instruments'),
        ),
    ]
