# Generated by Django 2.0.4 on 2018-05-22 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0005_remove_instruments_id_sale'),
        ('sales', '0005_sale_id_sale_instrument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='id_sale_Instrument',
        ),
        migrations.AddField(
            model_name='sale',
            name='id_sale_Instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.Instruments'),
        ),
    ]
