# Generated by Django 2.0.4 on 2018-05-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20180522_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='id_sale_Instrument',
            field=models.ForeignKey(on_delete=False, to='instruments.Instruments'),
        ),
    ]
