# Generated by Django 2.0.4 on 2018-05-22 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20180522_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='id_sale_Instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.Instruments'),
        ),
    ]
