# Generated by Django 2.0.4 on 2018-05-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20180522_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='Model_instrument',
            field=models.CharField(default='jojojojjo', max_length=25),
        ),
    ]
