# Generated by Django 2.0.4 on 2018-05-24 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_sale_model_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
