# Generated by Django 2.0.4 on 2018-05-24 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_sale_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='Date_sale',
        ),
    ]
