# Generated by Django 2.0.4 on 2018-05-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0005_remove_instruments_id_sale'),
        ('sales', '0013_sale_date_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='id_sale_Instrument',
        ),
        migrations.AddField(
            model_name='sale',
            name='id_sale_Instrument',
            field=models.ManyToManyField(to='instruments.Instruments'),
        ),
    ]
