# Generated by Django 2.0.4 on 2018-05-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20180524_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='Model_instrument',
            field=models.CharField(max_length=25),
        ),
    ]
