# Generated by Django 2.0.4 on 2018-05-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_auto_20180526_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='Id_user',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='Model_instrument',
        ),
    ]
