# Generated by Django 2.0.4 on 2018-05-28 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20180527_2251'),
        ('sales', '0016_auto_20180526_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='Client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persona.User'),
        ),
    ]
