# Generated by Django 2.0.4 on 2018-05-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_sale_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='Price_sale',
            field=models.FloatField(null=True),
        ),
    ]
