# Generated by Django 2.0.4 on 2018-05-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20180521_2205'),
        ('instruments', '0003_instruments_id_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruments',
            name='id_Sale',
        ),
        migrations.AddField(
            model_name='instruments',
            name='id_Sale',
            field=models.ManyToManyField(to='sales.Sale'),
        ),
    ]
