# Generated by Django 2.0.4 on 2018-05-21 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_auto_20180521_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruments',
            name='id_Sale',
        ),
    ]
