# Generated by Django 2.0.4 on 2018-05-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0005_remove_instruments_id_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruments',
            name='Production',
            field=models.FloatField(default=0),
        ),
    ]
