# Generated by Django 2.0.4 on 2018-05-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_instruments_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruments',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
