# Generated by Django 2.0.4 on 2018-05-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0007_auto_20180528_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruments',
            name='Quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
