# Generated by Django 2.0.4 on 2018-05-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0008_auto_20180528_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruments',
            name='Price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
