# Generated by Django 2.0.4 on 2018-05-28 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Born_Date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='admission_Date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='power',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salary',
        ),
    ]
