# Generated by Django 2.0.4 on 2018-05-25 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0001_initial'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='id_mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mark.Mark'),
        ),
    ]
